version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.guava:guava
    versions:
    - "> 27.1-jre"
  - dependency-name: com.google.guava:guava-gwt
    versions:
    - "> 27.1-jre"
  - dependency-name: com.google.guava:guava-testlib
    versions:
    - "> 27.1-jre"
  - dependency-name: com.google.inject:guice
    versions:
    - ">= 4.a, < 5"
  - dependency-name: org.antlr:antlr-runtime
    versions:
    - "> 3.2"
  - dependency-name: io.github.classgraph:classgraph
    versions:
    - 4.8.102
    - 4.8.103
  - dependency-name: com.google.errorprone:error_prone_annotations
    versions:
    - 2.5.1
  - dependency-name: org.eclipse.emf:org.eclipse.emf.common
    versions:
    - 2.21.0
  - dependency-name: org.eclipse.emf:org.eclipse.emf.codegen.ecore
    versions:
    - 2.24.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.eclipse.platform:org.eclipse.equinox.app
    versions:
    - 1.5.0
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
